# Generated by Django 5.2.6 on 2025-09-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirts'), ('J', 'Jeans'), ('F', 'Footwear'), ('W', 'Watches')], max_length=2),
        ),
    ]
