# Generated by Django 5.2.6 on 2025-09-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
