# Generated by Django 5.2.6 on 2025-09-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_embedding_userlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='refund_granted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_requested',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
